// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPVKgnvtkec7p8Ft5KrIBlaPydAx1ON0',
    appId: '1:1001674437793:web:2a23e2edcb238fda342ce0',
    messagingSenderId: '1001674437793',
    projectId: 'duanwashouse',
    authDomain: 'duanwashouse.firebaseapp.com',
    storageBucket: 'duanwashouse.firebasestorage.app',
    measurementId: 'G-JGL68W36CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD61k5t5vgVxNwA2G4FIfvcsQs41vCtz78',
    appId: '1:1001674437793:android:42076cade9051a38342ce0',
    messagingSenderId: '1001674437793',
    projectId: 'duanwashouse',
    storageBucket: 'duanwashouse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCag9CS8hUWf0R4pFD5ZTNlARa73w6hbdA',
    appId: '1:1001674437793:ios:ab713a1cbc1e2bf0342ce0',
    messagingSenderId: '1001674437793',
    projectId: 'duanwashouse',
    storageBucket: 'duanwashouse.firebasestorage.app',
    iosBundleId: 'com.example.warehouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCag9CS8hUWf0R4pFD5ZTNlARa73w6hbdA',
    appId: '1:1001674437793:ios:ab713a1cbc1e2bf0342ce0',
    messagingSenderId: '1001674437793',
    projectId: 'duanwashouse',
    storageBucket: 'duanwashouse.firebasestorage.app',
    iosBundleId: 'com.example.warehouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyPVKgnvtkec7p8Ft5KrIBlaPydAx1ON0',
    appId: '1:1001674437793:web:06a4ac3c7f0cd980342ce0',
    messagingSenderId: '1001674437793',
    projectId: 'duanwashouse',
    authDomain: 'duanwashouse.firebaseapp.com',
    storageBucket: 'duanwashouse.firebasestorage.app',
    measurementId: 'G-Q2JTB8X7XP',
  );
}
